// Auto-generated from serenbanka_sql.sql — do not edit manually
export const plot = [
  {
    "plot_id": 0,
    "text": "",
    "sayingpeople": "",
    "right_face": "",
    "read_people": "",
    "read_face": "",
    "left_people": "",
    "left_face": "",
    "middle_people": "",
    "middle_face": "",
    "right_people": "",
    "jump": -1,
    "isto": -1,
    "left_pose": "",
    "middle_pose": null,
    "right_pose": null,
    "read_pose": null,
    "left_pose_type": null,
    "read_pose_type": null,
    "right_pose_type": null,
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 1,
    "text": "迷糊地睁开眼",
    "sayingpeople": "",
    "right_face": null,
    "read_people": null,
    "read_face": null,
    "left_people": null,
    "left_face": null,
    "middle_people": null,
    "middle_face": null,
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": null,
    "right_pose": null,
    "read_pose": null,
    "left_pose_type": null,
    "read_pose_type": null,
    "right_pose_type": null,
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 2,
    "text": "「......」",
    "sayingpeople": "「player」",
    "right_face": null,
    "read_people": null,
    "read_face": null,
    "left_people": null,
    "left_face": null,
    "middle_people": null,
    "middle_face": null,
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": null,
    "right_pose": null,
    "read_pose": null,
    "left_pose_type": null,
    "read_pose_type": null,
    "right_pose_type": null,
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 3,
    "text": "这里看起来像是谁的房间…，我记得剧情开场也不是这样的吧,先四处转转好了…",
    "sayingpeople": null,
    "right_face": null,
    "read_people": null,
    "read_face": null,
    "left_people": null,
    "left_face": null,
    "middle_people": null,
    "middle_face": null,
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": null,
    "right_pose": null,
    "read_pose": null,
    "left_pose_type": null,
    "read_pose_type": "",
    "right_pose_type": null,
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 4,
    "text": "突然传出了某人开门的声音",
    "sayingpeople": "",
    "right_face": null,
    "read_people": "",
    "read_face": "",
    "left_people": null,
    "left_face": null,
    "middle_people": "",
    "middle_face": "",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "",
    "right_pose": null,
    "read_pose": "",
    "left_pose_type": null,
    "read_pose_type": "",
    "right_pose_type": null,
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 5,
    "text": "「ciallo!」",
    "sayingpeople": "「???」",
    "right_face": null,
    "read_people": "0",
    "read_face": "1",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "1",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "0",
    "right_pose": null,
    "read_pose": "0",
    "left_pose_type": null,
    "read_pose_type": "a",
    "right_pose_type": null,
    "middle_pose_type": "a",
    "sound": null,
    "voice": "ciallo",
    "music": "05"
  },
  {
    "plot_id": 6,
    "text": "!!!!!!",
    "sayingpeople": "「player」",
    "right_face": null,
    "read_people": "",
    "read_face": "",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "1",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "0",
    "right_pose": null,
    "read_pose": "",
    "left_pose_type": null,
    "read_pose_type": "",
    "right_pose_type": null,
    "middle_pose_type": "a",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 7,
    "text": "「哼哼，寒暄就到此为止了player，我的名字是丛雨，游戏《千恋万花》的主人公之一。」",
    "sayingpeople": "「丛雨」",
    "right_face": null,
    "read_people": "0",
    "read_face": "8",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "8",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "0",
    "right_pose": null,
    "read_pose": "0",
    "left_pose_type": null,
    "read_pose_type": "b",
    "right_pose_type": null,
    "middle_pose_type": "b",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 8,
    "text": "「想必你一定听过我的鼎鼎大名吧。初次见面请多关照。」",
    "sayingpeople": "「丛雨」",
    "right_face": null,
    "read_people": "0",
    "read_face": "9",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "9",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "1",
    "right_pose": null,
    "read_pose": "1",
    "left_pose_type": null,
    "read_pose_type": "b",
    "right_pose_type": null,
    "middle_pose_type": "b",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 9,
    "text": "「从雨小姐，这是怎么回事？」",
    "sayingpeople": "「player」",
    "right_face": null,
    "read_people": "",
    "read_face": "",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "8",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "1",
    "right_pose": null,
    "read_pose": "",
    "left_pose_type": null,
    "read_pose_type": "",
    "right_pose_type": null,
    "middle_pose_type": "b",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 10,
    "text": "「咳咳，这是因为这个web游戏复刻组的成员们是群杂鱼。」",
    "sayingpeople": "「丛雨」",
    "right_face": null,
    "read_people": "0",
    "read_face": "10",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "10",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "0",
    "right_pose": null,
    "read_pose": "0",
    "left_pose_type": null,
    "read_pose_type": "b",
    "right_pose_type": null,
    "middle_pose_type": "b",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 11,
    "text": "「时间和精力有限，素材也收集不齐，只能由我丛雨大人出马改成介绍剧情了。」",
    "sayingpeople": "「丛雨」",
    "right_face": null,
    "read_people": "0",
    "read_face": "7",
    "left_people": null,
    "left_face": null,
    "middle_people": "0",
    "middle_face": "7",
    "right_people": null,
    "jump": -1,
    "isto": -1,
    "left_pose": null,
    "middle_pose": "0",
    "right_pose": null,
    "read_pose": "0",
    "left_pose_type": null,
    "read_pose_type": "b",
    "right_pose_type": null,
    "middle_pose_type": "b",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 12,
    "text": "「失礼了。在下朝武芳乃。用Web重现穗织町，实为一项艰巨的修行。」",
    "sayingpeople": "「芳乃」",
    "right_face": "7",
    "read_people": "1",
    "read_face": "0",
    "left_people": "1",
    "left_face": "0",
    "middle_people": "",
    "middle_face": "",
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": "",
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "a",
    "read_pose_type": "a",
    "right_pose_type": "b",
    "middle_pose_type": "",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 13,
    "text": "「所以…这个网页是一个游戏复刻？」",
    "sayingpeople": "「player」",
    "right_face": "8",
    "read_people": "",
    "read_face": "",
    "left_people": "1",
    "left_face": "0",
    "middle_people": "",
    "middle_face": "",
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": "",
    "right_pose": "0",
    "read_pose": "",
    "left_pose_type": "a",
    "read_pose_type": "",
    "right_pose_type": "b",
    "middle_pose_type": "",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 14,
    "text": "「答对啦！是用Vue3作为前端框架，Pinia处理全局数据，利用Vue的响应式特性注入灵魂的舞台！」",
    "sayingpeople": "「丛雨」",
    "right_face": "9",
    "read_people": "0",
    "read_face": "9",
    "left_people": "1",
    "left_face": "0",
    "middle_people": "",
    "middle_face": "",
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": "",
    "right_pose": "1",
    "read_pose": "1",
    "left_pose_type": "a",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": "",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 15,
    "text": "「player体验到的实时界面的流畅加载靠的就是它哦!」",
    "sayingpeople": "「丛雨」",
    "right_face": "8",
    "read_people": "0",
    "read_face": "8",
    "left_people": "1",
    "left_face": "0",
    "middle_people": "",
    "middle_face": "",
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": "",
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "a",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": "",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 16,
    "text": "「核心难点在于前端庞大且复杂的交互逻辑和剧情分支树系统的数据库设计。」",
    "sayingpeople": "「芳乃」",
    "right_face": "8",
    "read_people": "1",
    "read_face": "0",
    "left_people": "1",
    "left_face": "0",
    "middle_people": "",
    "middle_face": "",
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": "",
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "a",
    "read_pose_type": "a",
    "right_pose_type": "b",
    "middle_pose_type": "",
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 17,
    "text": "「我们使用建立父子结点的方式管理分支剧情，player的每个选择都将改变故事流向。」",
    "sayingpeople": "「芳乃」",
    "right_face": "8",
    "read_people": "1",
    "read_face": "5",
    "left_people": "1",
    "left_face": "5",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 18,
    "text": "「能否展示下效果呢？」",
    "sayingpeople": "「player」",
    "right_face": "8",
    "read_people": "",
    "read_face": "",
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "",
    "left_pose_type": "b",
    "read_pose_type": "",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 19,
    "text": "「当然可以，还请随意。」",
    "sayingpeople": "「芳乃」",
    "right_face": "8",
    "read_people": "1",
    "read_face": "6",
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 20,
    "text": "",
    "sayingpeople": "",
    "right_face": "8",
    "read_people": "",
    "read_face": "",
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": 1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": null,
    "left_pose_type": "b",
    "read_pose_type": null,
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 21,
    "text": "「这个嘛...他们说着什么千原万神启动什么的就决定下来了，还说什么重铸呃次元荣光在此一举 …」",
    "sayingpeople": "「丛雨」",
    "right_face": "7",
    "read_people": "0",
    "read_face": "7",
    "left_people": "1",
    "left_face": "0",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 22,
    "text": "逆天柚子÷…",
    "sayingpeople": "「player」",
    "right_face": "10",
    "read_people": "",
    "read_face": "",
    "left_people": "1",
    "left_face": "1",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": 24,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "",
    "left_pose_type": "b",
    "read_pose_type": "",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 23,
    "text": "「什么，player你居然选择了跳过人生，那可是错过了世界级剧情对话文案哦」",
    "sayingpeople": "「丛雨」",
    "right_face": "3",
    "read_people": "0",
    "read_face": "3",
    "left_people": "1",
    "left_face": "3",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "b",
    "read_pose_type": "a",
    "right_pose_type": "a",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 24,
    "text": "「咳咳，不过话说回来看起来还真有模有样的？」",
    "sayingpeople": "「player」",
    "right_face": "8",
    "read_people": "",
    "read_face": "",
    "left_people": "1",
    "left_face": "5",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "",
    "left_pose_type": "b",
    "read_pose_type": "",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 25,
    "text": "「并非如此...因为解包素材不全，本大人的必杀技丛雨丸没有动画只能放仓库吃灰了...」",
    "sayingpeople": "「丛雨」",
    "right_face": "10",
    "read_people": "0",
    "read_face": "10",
    "left_people": "1",
    "left_face": "2",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 26,
    "text": "「简直是杂鱼级别的妥协的说」",
    "sayingpeople": "「丛雨」",
    "right_face": "7",
    "read_people": "0",
    "read_face": "7",
    "left_people": "1",
    "left_face": "0",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 27,
    "text": "「…但关键功能已实现。利用Vue的Pinia全局状态管理库进行界面间存档读档的数据传递和全局音乐的改变」",
    "sayingpeople": "「芳乃」",
    "right_face": "8",
    "read_people": "1",
    "read_face": "5",
    "left_people": "1",
    "left_face": "5",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 28,
    "text": "「如同用太鼓调动全祭典的氛围」",
    "sayingpeople": "「芳乃」",
    "right_face": "8",
    "read_people": "1",
    "read_face": "6",
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 29,
    "text": "「开发过程顺利吗？」",
    "sayingpeople": "「player」",
    "right_face": "4",
    "read_people": "",
    "read_face": "",
    "left_people": "1",
    "left_face": "0",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "",
    "left_pose_type": "b",
    "read_pose_type": "",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 30,
    "text": "「BUG多到爆炸...player你现在按下F11退出全屏的话估计就能观察到我们全都错位了，他们根本没做屏幕尺寸适配」",
    "sayingpeople": "「丛雨」",
    "right_face": "11",
    "read_people": "0",
    "read_face": "11",
    "left_people": "1",
    "left_face": "0",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 31,
    "text": "「更杂鱼的是他们居然想砍掉了我的动画特效！说什么加animation太浪费时间了」",
    "sayingpeople": "「丛雨」",
    "right_face": "12",
    "read_people": "0",
    "read_face": "12",
    "left_people": "1",
    "left_face": "5",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 32,
    "text": "「本大人可是500岁的付丧神，竟然沦落到和连膝盖都没有，无法原地起跳的魂5坐一桌了」",
    "sayingpeople": "「丛雨」",
    "right_face": "5",
    "read_people": "0",
    "read_face": "5",
    "left_people": "1",
    "left_face": "5",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "b",
    "read_pose_type": "a",
    "right_pose_type": "a",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 33,
    "text": "丛雨大人...还...还请您专注于项目说明！",
    "sayingpeople": "「芳乃」",
    "right_face": "5",
    "read_people": "1",
    "read_face": "1",
    "left_people": "1",
    "left_face": "1",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "a",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 34,
    "text": "哎，又幻想了...凭借废萌白开水剧情人设拿到2016年getchu游戏大赏女主角第一名，力压朝武芳乃和南梁飞鸟奏，创造一个......",
    "sayingpeople": "「丛雨」",
    "right_face": "4",
    "read_people": "0",
    "read_face": "4",
    "left_people": "1",
    "left_face": "1",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "0",
    "left_pose_type": "b",
    "read_pose_type": "a",
    "right_pose_type": "a",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 35,
    "text": "咳咳，那么最终成果如何？",
    "sayingpeople": "「player」",
    "right_face": "4",
    "read_people": null,
    "read_face": null,
    "left_people": "1",
    "left_face": "0",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "0",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": null,
    "left_pose_type": "b",
    "read_pose_type": null,
    "right_pose_type": "a",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 36,
    "text": "虽交互未能尽善尽美…但已充分证明，Web技术足以承载Galgame的核心叙事与互动体验。",
    "sayingpeople": "「芳乃」",
    "right_face": "8",
    "read_people": "1",
    "read_face": "6",
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 37,
    "text": "未来有计划更新吗？",
    "sayingpeople": "「player」",
    "right_face": "8",
    "read_people": null,
    "read_face": null,
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": null,
    "left_pose_type": "b",
    "read_pose_type": null,
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 38,
    "text": "当然有！下次更新就给player加入触摸交互！点我额头就能触发alert(\\\"无路赛！\\\")警告！",
    "sayingpeople": "「丛雨」",
    "right_face": "5",
    "read_people": "0",
    "read_face": "5",
    "left_people": "1",
    "left_face": "2",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "0",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 39,
    "text": "否决。当务之急是完善画面尺寸匹配以及考虑如何做到长剧情数据分表存储…",
    "sayingpeople": "「芳乃」",
    "right_face": "12",
    "read_people": "`1",
    "read_face": "4",
    "left_people": "1",
    "left_face": "4",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": "1",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 40,
    "text": "...现在有地方可以体验这个项目吗？",
    "sayingpeople": "「player」",
    "right_face": "8",
    "read_people": null,
    "read_face": null,
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "0",
    "read_pose": null,
    "left_pose_type": "b",
    "read_pose_type": null,
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  },
  {
    "plot_id": 41,
    "text": "去GitHub搜索“serenbanka:for learning”吧！记得给仓库点个星星哦～Ciallo～(∠・ω<)⌒★！",
    "sayingpeople": "「丛雨」",
    "right_face": "0",
    "read_people": "0",
    "read_face": "0",
    "left_people": "1",
    "left_face": "6",
    "middle_people": null,
    "middle_face": null,
    "right_people": "0",
    "jump": -1,
    "isto": -1,
    "left_pose": "1",
    "middle_pose": null,
    "right_pose": "1",
    "read_pose": "0",
    "left_pose_type": "b",
    "read_pose_type": "b",
    "right_pose_type": "b",
    "middle_pose_type": null,
    "sound": null,
    "voice": null,
    "music": "05"
  }
];

export const main = [
  {
    "plot_id": 0,
    "background": "画面_黒.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 1,
    "background": "画面_黒.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 2,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 3,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 4,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 5,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 6,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 7,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 8,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 9,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 10,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 11,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 12,
    "background": "朝武_自室B.png",
    "chapter": "1-1"
  },
  {
    "plot_id": 13,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 14,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 15,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 16,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 17,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 18,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 19,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 20,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 21,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 22,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 23,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 24,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 25,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 26,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 27,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 28,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 29,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 30,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 31,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 32,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 33,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 34,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 35,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 36,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 37,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 38,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 39,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 40,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  },
  {
    "plot_id": 41,
    "background": "朝武_自室B.png",
    "chapter": "1-2"
  }
];

export const jump = [
  {
    "jump": 1,
    "plot_id1": 21,
    "plot_id2": 23,
    "optionText1": "为什么选择了这个比较另类的题材？",
    "optionText2": "跳过",
    "stroyArc1": 1,
    "stroyArc2": 2
  }
];
